version: '3.1'

services:

  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: th4n0s
    ports:
      - 27017:27017
    volumes:
      - db-mongo:/data/db
      - config-db-mongo:/data/configdb

volumes:
  db-mongo:
  config-db-mongo: